"""
ArbWethUsdcMomentum Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import ArbWethUsdcMomentumStrategy
except ImportError:
    from strategy import ArbWethUsdcMomentumStrategy

__all__ = [
    "ArbWethUsdcMomentumStrategy",
]
